/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tf;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author Student
 */
public class Friends extends javax.swing.JFrame {

    /**
     * Creates new form Friends
     */
    public Friends() {
        initComponents();
        
            // 🔍 LIVE SEARCH (Google-like)
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                filterFriends(jTextField1.getText());
            }

            public void removeUpdate(DocumentEvent e) {
                filterFriends(jTextField1.getText());
            }

            public void changedUpdate(DocumentEvent e) {}
        });      
    }
        private void filterFriends(String query) {
        query = query.toLowerCase();

        javax.swing.JLabel[] labels = {panelMarl, panelPrince, panelBarch, panelKurt, panelSelwyn};
        javax.swing.JLabel[] images = {Shrek, Minecraft, Kulot, Chinese, Pogi};
        javax.swing.JButton[] accepts = {Accept1, Accept2, Accept3, Accept4, Accept5};
        javax.swing.JButton[] declines = {Decline1, Decline2, Decline3, Decline4, Decline5};

        for (int i = 0; i < labels.length; i++) {
            boolean match = labels[i].getText().toLowerCase().contains(query) || query.isEmpty();
            labels[i].setVisible(match);
            images[i].setVisible(match);
            accepts[i].setVisible(match);
            declines[i].setVisible(match);
        }

        jPanel1.revalidate();
        jPanel1.repaint();
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Shrek = new javax.swing.JLabel();
        panelMarl = new javax.swing.JLabel();
        Accept1 = new javax.swing.JButton();
        Decline1 = new javax.swing.JButton();
        Minecraft = new javax.swing.JLabel();
        panelPrince = new javax.swing.JLabel();
        Accept2 = new javax.swing.JButton();
        Decline2 = new javax.swing.JButton();
        Kulot = new javax.swing.JLabel();
        Decline3 = new javax.swing.JButton();
        Accept3 = new javax.swing.JButton();
        Accept4 = new javax.swing.JButton();
        panelBarch = new javax.swing.JLabel();
        Chinese = new javax.swing.JLabel();
        Decline4 = new javax.swing.JButton();
        panelKurt = new javax.swing.JLabel();
        Accept5 = new javax.swing.JButton();
        Decline5 = new javax.swing.JButton();
        Pogi = new javax.swing.JLabel();
        panelSelwyn = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 500));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Friend Requests");

        Shrek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tf/shrek.png"))); // NOI18N

        panelMarl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        panelMarl.setForeground(new java.awt.Color(0, 0, 0));
        panelMarl.setText("Marl Concepcion");

        Accept1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Accept1.setForeground(new java.awt.Color(0, 0, 0));
        Accept1.setText("Accept");
        Accept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accept1ActionPerformed(evt);
            }
        });

        Decline1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Decline1.setForeground(new java.awt.Color(0, 0, 0));
        Decline1.setText("Decline");
        Decline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decline1ActionPerformed(evt);
            }
        });

        Minecraft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tf/game.png"))); // NOI18N

        panelPrince.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        panelPrince.setForeground(new java.awt.Color(0, 0, 0));
        panelPrince.setText("Prince Andrei Osian");

        Accept2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Accept2.setForeground(new java.awt.Color(0, 0, 0));
        Accept2.setText("Accept");
        Accept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accept2ActionPerformed(evt);
            }
        });

        Decline2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Decline2.setForeground(new java.awt.Color(0, 0, 0));
        Decline2.setText("Decline");
        Decline2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decline2ActionPerformed(evt);
            }
        });

        Kulot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tf/boy.png"))); // NOI18N

        Decline3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Decline3.setForeground(new java.awt.Color(0, 0, 0));
        Decline3.setText("Decline");
        Decline3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decline3ActionPerformed(evt);
            }
        });

        Accept3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Accept3.setForeground(new java.awt.Color(0, 0, 0));
        Accept3.setText("Accept");
        Accept3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accept3ActionPerformed(evt);
            }
        });

        Accept4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Accept4.setForeground(new java.awt.Color(0, 0, 0));
        Accept4.setText("Accept");
        Accept4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accept4ActionPerformed(evt);
            }
        });

        panelBarch.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        panelBarch.setForeground(new java.awt.Color(0, 0, 0));
        panelBarch.setText("Barch Palpeg");

        Chinese.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        Chinese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tf/chinese.png"))); // NOI18N

        Decline4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Decline4.setForeground(new java.awt.Color(0, 0, 0));
        Decline4.setText("Decline");
        Decline4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decline4ActionPerformed(evt);
            }
        });

        panelKurt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        panelKurt.setForeground(new java.awt.Color(0, 0, 0));
        panelKurt.setText("Kurt Ivan Castro");

        Accept5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Accept5.setForeground(new java.awt.Color(0, 0, 0));
        Accept5.setText("Accept");
        Accept5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accept5ActionPerformed(evt);
            }
        });

        Decline5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Decline5.setForeground(new java.awt.Color(0, 0, 0));
        Decline5.setText("Decline");
        Decline5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decline5ActionPerformed(evt);
            }
        });

        Pogi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tf/handsome.png"))); // NOI18N

        panelSelwyn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        panelSelwyn.setForeground(new java.awt.Color(0, 0, 0));
        panelSelwyn.setText("Selwyn Pogi");

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tf/left-arrow.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Enter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Minecraft, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Accept2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Decline2))
                                    .addComponent(panelPrince)))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Kulot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Accept3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Decline3))
                                    .addComponent(panelBarch)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Shrek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelMarl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Accept1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Decline1)))))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(Accept4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Decline4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Pogi)
                                    .addComponent(Chinese))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelKurt)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Accept5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Decline5))
                                    .addComponent(panelSelwyn)))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelMarl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Accept1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Decline1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Shrek))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelPrince)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Accept2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Decline2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Minecraft, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelBarch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Accept3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Decline3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Kulot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(panelKurt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Accept4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Decline4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Chinese))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pogi)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(panelSelwyn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Accept5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Decline5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(266, 266, 266))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Accept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accept1ActionPerformed
    JOptionPane.showMessageDialog(this, "Friend request accepted!"); 
    panelMarl.setVisible(false);
    Shrek.setVisible(false);
    Accept1.setVisible(false);
    Decline1.setVisible(false);
    }//GEN-LAST:event_Accept1ActionPerformed

    private void Decline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decline1ActionPerformed
    JOptionPane.showMessageDialog(this, "Friend request declined!"); 
    panelMarl.setVisible(false);
    Shrek.setVisible(false);
    Accept1.setVisible(false); 
    Decline1.setVisible(false);
    }//GEN-LAST:event_Decline1ActionPerformed

    private void Accept2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accept2ActionPerformed
    JOptionPane.showMessageDialog(this, "Friend request accepted!"); 
    panelPrince.setVisible(false);
    Minecraft.setVisible(false);
    Accept2.setVisible(false);
    Decline2.setVisible(false);
    }//GEN-LAST:event_Accept2ActionPerformed

    private void Decline2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decline2ActionPerformed
    JOptionPane.showMessageDialog(this, "Friend request declined!"); 
    panelPrince.setVisible(false);
    Minecraft.setVisible(false);
    Accept2.setVisible(false);
    Decline2.setVisible(false);    
    }//GEN-LAST:event_Decline2ActionPerformed

    private void Accept3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accept3ActionPerformed
    JOptionPane.showMessageDialog(this, "Friend request accepted!"); 
    panelBarch.setVisible(false);
    Kulot.setVisible(false);
    Accept3.setVisible(false);
    Decline3.setVisible(false);
    }//GEN-LAST:event_Accept3ActionPerformed

    private void Decline3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decline3ActionPerformed
    JOptionPane.showMessageDialog(this, "Friend request declined!"); 
    panelBarch.setVisible(false);
    Kulot.setVisible(false);
    Accept3.setVisible(false);
    Decline3.setVisible(false);    
    }//GEN-LAST:event_Decline3ActionPerformed

    private void Accept4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accept4ActionPerformed
    JOptionPane.showMessageDialog(this, "Friend request accepted!"); 
    panelKurt.setVisible(false);
    Chinese.setVisible(false);
    Accept4.setVisible(false);
    Decline4.setVisible(false);       
    }//GEN-LAST:event_Accept4ActionPerformed

    private void Decline4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decline4ActionPerformed
   JOptionPane.showMessageDialog(this, "Friend request declined!"); 
    panelKurt.setVisible(false);
    Chinese.setVisible(false);
    Accept4.setVisible(false);
    Decline4.setVisible(false);   
    }//GEN-LAST:event_Decline4ActionPerformed

    private void Accept5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accept5ActionPerformed
    JOptionPane.showMessageDialog(this, "Friend request accepted!"); 
    panelSelwyn.setVisible(false);
    Pogi.setVisible(false);
    Accept5.setVisible(false);
    Decline5.setVisible(false);  
    }//GEN-LAST:event_Accept5ActionPerformed

    private void Decline5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decline5ActionPerformed
   JOptionPane.showMessageDialog(this, "Friend request declined!"); 
    panelSelwyn.setVisible(false);
    Pogi.setVisible(false);
    Accept5.setVisible(false);
    Decline5.setVisible(false);    
    }//GEN-LAST:event_Decline5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new TeamsFriends().setVisible(true);
    setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    new Friends2().setVisible(true);  
    dispose();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
      filterFriends(jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Friends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept1;
    private javax.swing.JButton Accept2;
    private javax.swing.JButton Accept3;
    private javax.swing.JButton Accept4;
    private javax.swing.JButton Accept5;
    private javax.swing.JLabel Chinese;
    private javax.swing.JButton Decline1;
    private javax.swing.JButton Decline2;
    private javax.swing.JButton Decline3;
    private javax.swing.JButton Decline4;
    private javax.swing.JButton Decline5;
    private javax.swing.JLabel Kulot;
    private javax.swing.JLabel Minecraft;
    private javax.swing.JLabel Pogi;
    private javax.swing.JLabel Shrek;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel panelBarch;
    private javax.swing.JLabel panelKurt;
    private javax.swing.JLabel panelMarl;
    private javax.swing.JLabel panelPrince;
    private javax.swing.JLabel panelSelwyn;
    // End of variables declaration//GEN-END:variables
}
